[font]
size = 14.0
# use_thin_strokes = true

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "MesloLGL Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[window]
dynamic_padding = true
